-- Matches docs/data/modelagem-de-dados.md's auth-db DDL exactly. This file
-- is generated by `prisma migrate dev` in every other respect; the partial
-- index at the bottom is added by hand, since Prisma's schema DSL cannot
-- express a WHERE clause on an index.

CREATE TABLE "users" (
  "id"            uuid         PRIMARY KEY,
  "name"          varchar(120) NOT NULL,
  "email"         varchar(255) NOT NULL UNIQUE,
  "password_hash" char(60)     NOT NULL,
  "created_at"    timestamptz  NOT NULL DEFAULT now(),
  "updated_at"    timestamptz  NOT NULL DEFAULT now()
);

CREATE TABLE "outbox" (
  "id"             uuid         PRIMARY KEY,
  "aggregate_type" varchar(50)  NOT NULL,
  "aggregate_id"   uuid         NOT NULL,
  "event_type"     varchar(100) NOT NULL,
  "version"        smallint     NOT NULL DEFAULT 1,
  "payload"        jsonb        NOT NULL,
  "correlation_id" uuid,
  "occurred_at"    timestamptz  NOT NULL DEFAULT now(),
  "published_at"   timestamptz,
  "attempts"       smallint     NOT NULL DEFAULT 0
);

-- Hand-written: the relay only ever queries pending rows, and most rows are
-- published within moments of being written. A partial index keeps it
-- small regardless of how much history accumulates in the table.
CREATE INDEX "idx_outbox_pendentes" ON "outbox" ("occurred_at") WHERE "published_at" IS NULL;
