sonar.organization=knzt
sonar.projectKey=knzt_zipframes-notifier-service
sonar.projectName=ZipFrames notifier-service

sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.exclusions=src/infrastructure/repositories/prisma/migrations/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPaths=tsconfig.json

sonar.coverage.exclusions=src/main/**,src/application/interfaces/**,src/domain/index.ts,src/infrastructure/http/**,src/infrastructure/repositories/**,src/infrastructure/messaging/amqplib/connection.ts,src/infrastructure/messaging/amqplib/contactEventsConsumer.ts,src/infrastructure/messaging/amqplib/emailEventsConsumer.ts,src/infrastructure/messaging/amqplib/peekEventType.ts
