apiVersion: v1
kind: Service
metadata:
  name: processor-worker
  namespace: zipframes
  labels:
    app: processor-worker
spec:
  selector:
    app: processor-worker
  ports:
    - name: health
      port: 8081
      targetPort: health
    - name: metrics
      port: 9091
      targetPort: metrics
