apiVersion: v1
kind: Secret
metadata:
  name: auth-service
  namespace: zipframes
type: Opaque
stringData:
  AUTH_DATABASE_URL: postgresql://zipframes:replace-me@auth-db-rw.zipframes.svc.cluster.local:5432/auth_db
  AMQP_URL: amqp://zipframes:replace-me@rabbitmq.zipframes.svc.cluster.local:5672
  JWT_PRIVATE_KEY_PEM: |
    -----BEGIN PRIVATE KEY-----
    replace-me
    -----END PRIVATE KEY-----
