apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring
spec:
  ingressClassName: traefik
  rules:
    - host: grafana.zipframes.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  name: http
    - host: prometheus.zipframes.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus-operated
                port:
                  name: web
    - host: alertmanager.zipframes.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: alertmanager-operated
                port:
                  name: web
