apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: video-service
  namespace: zipframes
spec:
  ingressClassName: traefik
  rules:
    - host: api.zipframes.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: video-service
                port:
                  name: http
