apiVersion: v1
kind: Service
metadata:
  name: video-service
  namespace: zipframes
  labels:
    app: video-service
spec:
  selector:
    app: video-service
  ports:
    - name: http
      port: 3001
      targetPort: http
