-- Matches docs/data/modelagem-de-dados.md's notification-db DDL. This file
-- is generated by `prisma migrate dev` in every other respect; the partial
-- index and CHECK constraints are added by hand, since Prisma's schema DSL
-- cannot express them.

CREATE TYPE "notification_type" AS ENUM ('VIDEO_PROCESSED', 'VIDEO_FAILED');
CREATE TYPE "notification_channel" AS ENUM ('EMAIL');
CREATE TYPE "notification_status" AS ENUM ('PENDING', 'SENT', 'FAILED');

CREATE TABLE "contacts" (
  "user_id"    uuid         PRIMARY KEY,
  "name"       varchar(120) NOT NULL,
  "email"      varchar(255) NOT NULL,
  "updated_at" timestamptz  NOT NULL DEFAULT now()
);

CREATE TABLE "notifications" (
  "id"                 uuid                  PRIMARY KEY,
  "user_id"            uuid                  NOT NULL,
  "video_id"           uuid                  NOT NULL,
  "type"               "notification_type"   NOT NULL,
  "channel"            "notification_channel" NOT NULL DEFAULT 'EMAIL',
  "status"             "notification_status" NOT NULL DEFAULT 'PENDING',
  "target"             varchar(255),
  "original_file_name" varchar(255)          NOT NULL,
  "result_key"         varchar(512),
  "frame_count"        integer,
  "uploaded_at"        timestamptz,
  "created_at"         timestamptz           NOT NULL DEFAULT now(),
  "sent_at"            timestamptz,
  CONSTRAINT "uq_notifications_video_tipo" UNIQUE ("video_id", "type"),
  CONSTRAINT "ck_notifications_sent" CHECK ("status" <> 'SENT' OR ("sent_at" IS NOT NULL AND "target" IS NOT NULL))
);

CREATE TABLE "notification_attempts" (
  "id"              uuid         PRIMARY KEY,
  "notification_id" uuid         NOT NULL REFERENCES "notifications" ("id") ON DELETE CASCADE,
  "attempt"         smallint     NOT NULL CHECK ("attempt" > 0),
  "target"          varchar(255) NOT NULL,
  "error"           text         NOT NULL,
  "attempted_at"    timestamptz  NOT NULL DEFAULT now(),
  CONSTRAINT "uq_attempts_notificacao" UNIQUE ("notification_id", "attempt")
);

CREATE INDEX "idx_notifications_user" ON "notifications" ("user_id", "created_at" DESC);

-- Hand-written: drain only ever queries PENDING rows.
CREATE INDEX "idx_notifications_pendentes" ON "notifications" ("created_at") WHERE "status" = 'PENDING';
