apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/knzt/zipframes.git
    targetRevision: main
    path: infra/k8s/auth-service
  destination:
    server: https://kubernetes.default.svc
    namespace: zipframes
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
